/**
 * tokenGenerator.js
 * ------------------------------------------------------
 * Simulates JWT token generation on the frontend.
 *
 * NOTE:
 * This is only for frontend/demo purposes.
 * In a real production application:
 * - Tokens should be generated by the backend
 * - Signatures should be cryptographically secure
 * - Secrets must never be exposed in frontend code
 *
 * Responsibilities:
 * 1. Create JWT-like token structure
 * 2. Encode header + payload using Base64URL
 * 3. Generate demo signature
 * 4. Store token/session data in storage
 *
 * Token Structure:
 * header.payload.signature
 */

// import storage, { STORAGE_KEYS } from '../../utils/storage'

import storage, { STORAGE_KEYS } from '../utils/storage'

/**
 * Token expiry duration in minutes.
 * Reads from environment variable.
 * Default: 5 minutes
 */
const EXPIRY_MINUTES =
  Number(import.meta.env.VITE_TOKEN_EXPIRY_MINUTES) || 5

/**
 * Demo secret key used for fake signing.
 * Never expose real secrets in frontend apps.
 */
const SECRET = import.meta.env.VITE_TOKEN_SECRET || 'dev_secret'

/**
 * Converts normal string into Base64URL format.
 *
 * Why Base64URL?
 * JWT uses URL-safe Base64 encoding:
 * + becomes -
 * / becomes _
 * = padding removed
 *
 * @param {string} str
 * @returns {string}
 */
const b64 = (str) =>
  btoa(unescape(encodeURIComponent(str)))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '')

/**
 * Creates simple demo signature.
 *
 * NOTE:
 * This is NOT secure cryptographic signing.
 * Used only for frontend JWT simulation.
 *
 * @param {string} data
 * @returns {string}
 */
const sign = (data) => b64(`${data}.${SECRET}`)

/**
 * Generates authentication token for logged-in user.
 *
 * Flow:
 * 1. Create token timestamps
 * 2. Generate JWT header
 * 3. Generate payload with user details
 * 4. Create fake signature
 * 5. Combine into JWT format
 * 6. Save token/session data in storage
 *
 * @param {Object} user
 * User object received after login
 *
 * @returns {string}
 * Generated JWT-like token
 */
export const generateToken = (user) => {
  // Current timestamp
  const now = Date.now()

  // Expiry timestamp
  const expiry = now + EXPIRY_MINUTES * 60 * 1000

  /**
   * JWT Header
   * alg = signing algorithm
   * typ = token type
   */
  const header = b64(
    JSON.stringify({
      alg: 'HS256',
      typ: 'JWT',
    })
  )

  /**
   * JWT Payload
   * Contains user/session information
   */
  const payload = b64(
    JSON.stringify({
      sub: user.id,                // Subject/User ID
      name: user.name,             // User name
      email: user.email,           // User email
      role: user.role || 'user',  // User role
      iat: now,                    // Issued at
      exp: expiry,                 // Expiration time
    })
  )

  // Generate demo signature
  const signature = sign(`${header}.${payload}`)

  // Final JWT-like token
  const token = `${header}.${payload}.${signature}`

  /**
   * Persist authentication data
   * so session survives page refresh.
   */
  storage.set(STORAGE_KEYS.AUTH_TOKEN, token)
  storage.set(STORAGE_KEYS.TOKEN_EXPIRY, expiry)
  storage.set(STORAGE_KEYS.USER, user)

  // Return generated token
  return token
}